INSERT INTO ACCOUNTS ("NAME", "BALANCE", "CCY") VALUES('My test account 1', 10000, 'RUB')
INSERT INTO ACCOUNTS ("NAME", "BALANCE", "CCY") VALUES('My test account 2', 10000, 'EUR')
INSERT INTO ACCOUNTS ("NAME", "BALANCE", "CCY") VALUES('My test account 3', 10000, 'USD')
